# Challenge Project: Hurricane Analysis

This code challenge and data are provided by Codecademy in the Data Scientist path. The 'official' solutions can be found [here](https://codecademy-content.s3.amazonaws.com/PRO/independent-practice-projects/hurricane-analysis/hurricane_analysis_ending.zip).

## Data

In [2]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie', 'Beulah', 'Camille', 'Edith', 'Anita', 'David', 'Allen', 'Gilbert', 'Hugo', 'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma', 'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September', 'September', 'September', 'September', 'October', 'September', 'August', 'September', 'September', 'August', 'August', 'September', 'September', 'August', 'October', 'September', 'September', 'July', 'August', 'September', 'October', 'August', 'September', 'October', 'September', 'September', 'October']

# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967, 1969, 1971, 1977, 1979, 1980, 1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160, 175, 160, 175, 175, 190, 185, 160, 175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], ['The Bahamas', 'Northeastern United States'], ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'], ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'], ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'], ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'], ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], ['Mexico'], ['The Caribbean', 'United States East coast'], ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], ['The Caribbean', 'United States East Coast'], ['The Bahamas', 'Florida', 'United States Gulf Coast'], ['Central America', 'Yucatn Peninsula', 'South Florida'], ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'], ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], ['Bahamas', 'United States Gulf Coast'], ['Cuba', 'United States Gulf Coast'], ['Greater Antilles', 'Central America', 'Florida'], ['The Caribbean', 'Central America'], ['Nicaragua', 'Honduras'], ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], ['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,65,19325,51,124,17,1836,125,87,45,133,603,138,3057,74]

## Challenge 2

Hurricanes, also known as cyclones or typhoons, are one of the most powerful forces of nature on Earth. Due to climate change caused by human activity, the number and intensity of hurricanes has risen, calling for better preparation by the many communities that are devastated by them. As a concerned environmentalist, you want to look at data about the most powerful hurricanes that have occurred.

Begin by looking at the damages list. The list contains strings representing the total cost in USD($) caused by 34 category 5 hurricanes (wind speeds ≥ 157 mph (252 km/h )) in the Atlantic region. For some of the hurricanes, damage data was not recorded ("Damages not recorded"), while the rest are written in the format "Prefix-B/M", where B stands for billions (1000000000) and M stands for millions (1000000).

Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as "Damages not recorded".

Test your function with the data stored in damages.

In [3]:
def convert_sums(variable):
    new_values = []
    for value in variable:
        if value[-1] == "M":
            new_values.append(float(value[:-1]) * 1000000)
        elif value[-1] == "B":
            new_values.append(float(value[:-1]) * 1000000000)
        else:
            new_values.append(value)
    return new_values
      
new_damages = convert_sums(damages)

print(new_damages)

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


## Challenge 3

Additional data collected on the 34 strongest Atlantic hurricanes are provided in a series of lists. The data includes:

names: names of the hurricanes
months: months in which the hurricanes occurred
years: years in which the hurricanes occurred
max_sustained_winds: maximum sustained winds (miles per hour) of the hurricanes
areas_affected: list of different areas affected by each of the hurricanes
deaths: total number of deaths caused by each of the hurricanes
The data is organized such that the data at each index, from 0 to 33, corresponds to the same hurricane.

For example, names[0] yields the “Cuba I” hurricane, which ouccred in months[0] (October) years[0] (1924).

Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data (Name, Month, Year,Max Sustained Wind, Areas Affected, Damage, Death) about the hurricane.

Thus the key "Cuba I" would have the value: {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}.

Test your function on the lists of data provided.

In [41]:
def construct_library_hurricanes(names, months, years, max_sustained_winds, areas_affected, new_damages, deaths):
    return {entry[0]: {"Month": entry[1], 
                       "Year": entry[2], 
                       "Max sustained winds": entry[3],
                       "Areas affected": entry[4], 
                       "Damages": entry[5], 
                       "Deaths": entry[6]} 
                  for entry in zip(names, 
                                   months, 
                                   years, 
                                   max_sustained_winds, 
                                   areas_affected, 
                                   new_damages, 
                                   deaths)}

# Store for later use
dict_hurricanes = construct_library_hurricanes(names, 
                                               months, 
                                               years, 
                                               max_sustained_winds, 
                                               areas_affected, 
                                               new_damages, 
                                               deaths) 

print(dict_hurricanes)        

{'Cuba I': {'Month': 'October', 'Year': 1924, 'Max sustained winds': 165, 'Areas affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damages': 'Damages not recorded', 'Deaths': 90}, 'San Felipe II Okeechobee': {'Month': 'September', 'Year': 1928, 'Max sustained winds': 160, 'Areas affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damages': 100000000.0, 'Deaths': 4000}, 'Bahamas': {'Month': 'September', 'Year': 1932, 'Max sustained winds': 160, 'Areas affected': ['The Bahamas', 'Northeastern United States'], 'Damages': 'Damages not recorded', 'Deaths': 16}, 'Cuba II': {'Month': 'November', 'Year': 1932, 'Max sustained winds': 175, 'Areas affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damages': 40000000.0, 'Deaths': 3103}, 'CubaBrownsville': {'Month': 'August', 'Year': 1933, 'Max sustained winds': 160, 'Areas affected': ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaul

## Challenge 4

In addition to organizing the hurricanes in a dictionary with names as the key, you want to be able to organize the hurricanes by year.

Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

For example, the key 1932 would yield the value: [{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}].

Test your function on your hurricane dictionary.

In [37]:
def convert_to_year(dictionary):
    return {dictionary[record]["Year"]: 
                         {"Name": record,
                          "Month": dictionary[record]["Month"],
                          "Year": dictionary[record]["Year"],
                          "Max sustained winds": dictionary[record]["Max sustained winds"],
                          "Areas affected": dictionary[record]["Areas affected"],
                          "Damage": dictionary[record]["Damages"],
                          "Deaths": dictionary[record]["Deaths"]} 
            for record in dictionary}

print(convert_to_year(dict_hurricanes))

{1924: {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max sustained winds': 165, 'Areas affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}, 1928: {'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max sustained winds': 160, 'Areas affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Deaths': 4000}, 1932: {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max sustained winds': 175, 'Areas affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}, 1933: {'Name': 'Tampico', 'Month': 'September', 'Year': 1933, 'Max sustained winds': 160, 'Areas affected': ['Jamaica', 'Yucatn Peninsula'], 'Damage': 5000000.0, 'Deaths': 184}, 1935: {'Name': 'Labor Day', 'Month': 'September', 'Year': 1935, 'Max sustained winds': 185, 'Areas affected': ['The Bahamas'

## Challenge 5

You believe that knowing how often each of the areas of the Atlantic are affected by these strong hurricanes is important for making preparations for future hurricanes.

Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.

Test your function on your hurricane dictionary.

In [35]:
def number_of_times_affected(dictionary):
    areas = []
    for entry in dictionary:
        areas += dictionary[entry]["Areas affected"]
    return {area: areas.count(area) for area in sorted(areas)}

dict_number_affected = number_of_times_affected(dict_hurricanes)
print(dict_number_affected)

# Tried this with list comprehension, but this yielded a list of lists rather than 1 long list 
# which was inconvenient for the count method

{'Antilles': 1, 'Atlantic Canada': 3, 'Bahamas': 2, 'Bermuda': 2, 'British Virgin Islands': 1, 'Cape Verde': 1, 'Cayman Islands': 1, 'Central America': 9, 'Colombia': 1, 'Cuba': 6, 'Dominican Republic': 1, 'Eastern United States': 1, 'Florida': 6, 'Georgia': 1, 'Greater Antilles': 2, 'Hispaniola': 1, 'Honduras': 1, 'Jamaica': 4, 'Lesser Antilles': 4, 'Louisiana': 1, 'Mexico': 7, 'Midwestern United States': 1, 'New England': 1, 'Nicaragua': 1, 'Northeastern United States': 2, 'Ontario': 1, 'Puerto Rico': 1, 'South Florida': 1, 'South Texas': 1, 'Southeastern United States': 1, 'Southwestern Quebec': 1, 'Tamaulipas': 1, 'Texas': 4, 'The Bahamas': 7, 'The Caribbean': 8, 'The Carolinas': 1, 'Turks and Caicos Islands': 1, 'U.S. Virgin Islands': 1, 'United States East Coast': 3, 'United States East coast': 1, 'United States Gulf Coast': 6, 'United States Gulf Coast (especially Florida Panhandle)': 1, 'Venezuela': 3, 'Virgin Islands': 1, 'Virginia': 1, 'Windward Islands': 1, 'Yucatn Peninsula

In [ ]:
areas = [item for area_list in dict_hurricanes for item in area_list]



## Challenge 6

Write a function that finds the area affected by the most hurricanes, and how often it was hit.

Test your function on your affected area dictionary.

In [23]:
def find_area_most_hit(dictionary):
    return {item[0]:item[1] for item in dictionary.items() if int(item[1]) == max(dictionary.values())}

most_affected = find_area_most_hit(dict_number_affected) # store dictionary for later use

print(most_affected)

{'Central America': 9}


## Challenge 7

Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

Test your function on your hurricane dictionary.

In [21]:
def find_hurricane_most_deaths(dictionary):
    deaths = {record: dictionary[record]["Deaths"] for record in dictionary}
    return {item[0]:item[1] for item in deaths.items() if int(item[1]) == max(deaths.values())}

print(find_hurricane_most_deaths(dict_hurricanes))

{'Mitch': 19325}


## Challenge 8

Just as hurricanes are rated by their windspeed, you want to try rating hurricanes based on other metrics.

Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

``` 
mortality_scale = {0: 0,
                   1: 100,
                   2: 500,
                   3: 1000,
                   4: 10000}
```

For example, a hurricane with a 1 mortality rating would have resulted in greater than 0 but less than or equal to 100 deaths. A hurricane with a 5 mortality rating would have resulted in greater than 10000 deaths.

Store the hurricanes in a new dictionary where the keys are mortality ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.

Test your function on your hurricane dictionary.

In [62]:
def mortality_rating(dictionary):
    deaths = {record: dictionary[record]["Deaths"] for record in dictionary}
    mortality_dict = {0: [], 1: [], 2: [], 3: [], 4: [], 5: []}
    for record in deaths.items():
        if int(record[1]) == 0:
            mortality_dict[0].append(record[0])
        if int(record[1]) > 0 and int(record[1]) < 100: 
            mortality_dict[1].append(record[0])
        elif int(record[1]) >= 100 and int(record[1]) < 500:
            mortality_dict[2].append(record[0])
        elif int(record[1]) >= 500 and int(record[1]) < 1000:
            mortality_dict[3].append(record[0])
        elif int(record[1]) >= 1000 and int(record[1]) < 10000:
            mortality_dict[4].append(record[0])
        else:
            mortality_dict[5].append(record[0])
    return mortality_dict

print(mortality_rating(dict_hurricanes))

{0: [], 1: ['Cuba I', 'Bahamas', 'Carol', 'Carla', 'Edith', 'Anita', 'Andrew', 'Isabel', 'Emily', 'Wilma', 'Dean', 'Michael'], 2: ['CubaBrownsville', 'Tampico', 'Labor Day', 'Hattie', 'Camille', 'Allen', 'Gilbert', 'Hugo', 'Ivan', 'Rita', 'Felix', 'Irma'], 3: ['New England', 'Beulah', 'Matthew'], 4: ['San Felipe II Okeechobee', 'Cuba II', 'Janet', 'David', 'Katrina', 'Maria'], 5: ['Mitch']}
